### ISSUE TITLE
Add kraken image registry

### ISSUE THREAD

**Issue by almesalati** [almesalati/Kraken#1]
# Todo
- [ ] configure a system-local registry that hosts docker images

- [ ] improve the registry security by adding authentication mechanisms 

- [ ]  configure all nodes to use `kraken-registry` as host name to the registry ip address 

- [ ]  add native support to Github container registry aka `ghcr.io`

- [ ]  check if the master node can pull images to other nodes so you just use `docker login` command on the master node only for you have to run it on each node separately
